### ISSUE TITLE
Backend TODO

### ISSUE THREAD

**Issue by FrederickGeek8** [Derek-Wds/UH-backend#1]
Here are some things that I thought of that we need to do (I will update it when I think of more)

- [x] Search patient by phone number
- [x] Medicines API (patient's medicine table, get medicines API, give medicine API)
- [x] Medicine remove or date range functionality (historical vs current)
- [x] Medicine reminder API
- [x] Illnesses Data API (add)
- [x] Illnesses Data API (get historical data)
- [ ] New registration form

**Comment by FrederickGeek8** [comment]
I removed the "Biometric Data API " requirement since we already cover that in our log system.

**Comment by FrederickGeek8** [comment]
I added "Medicine remove or date range functionality". Basically, we need to choose whether to display historical data for medication, which means we would need to store a beginning/end date for the medication, or we decide to only have current medication there, in which case we should have a remove medication functionality. 

I personally think historical medicine data makes more sense for our application.
